
export const getQuestions = async () => {
  return [
    // --- REACT (25 Questions) ---
    { subject: "react", question: "What is React?", options: ["Library", "Framework", "Language"], correctAnswer: "Library" },
    { subject: "react", question: "What is useState?", options: ["Hook", "API", "Library"], correctAnswer: "Hook" },
    { subject: "react", question: "Which is used to increase performance?", options: ["Original DOM", "Virtual DOM", "Both"], correctAnswer: "Virtual DOM" },
    { subject: "react", question: "Which hook is used for side effects?", options: ["useEffect", "useState", "useContext"], correctAnswer: "useEffect" },
    { subject: "react", question: "What is JSX?", options: ["JavaScript XML", "JSON Extension", "Java Syntax"], correctAnswer: "JavaScript XML" },
    { subject: "react", question: "How do you pass data to a child component?", options: ["Props", "State", "Hooks"], correctAnswer: "Props" },
    { subject: "react", question: "What is the default port for React development?", options: ["3000", "8080", "5000"], correctAnswer: "3000" },
    { subject: "react", question: "Which command creates a new React app?", options: ["npx create-react-app", "npm install react", "node create-app"], correctAnswer: "npx create-react-app" },
    { subject: "react", question: "What is a 'key' prop used for?", options: ["Identifying list elements", "Styling", "Data Binding"], correctAnswer: "Identifying list elements" },
    { subject: "react", question: "Which hook memoizes expensive calculations?", options: ["useMemo", "useCallback", "useRef"], correctAnswer: "useMemo" },
    { subject: "react", question: "What is the use of 'useContext'?", options: ["Global State", "Local State", "Direct DOM access"], correctAnswer: "Global State" },
    { subject: "react", question: "What is a Fragment?", options: ["Wrapper without a DOM node", "A small component", "A logic error"], correctAnswer: "Wrapper without a DOM node" },
    { subject: "react", question: "Can hooks be used in class components?", options: ["No", "Yes", "Only in special cases"], correctAnswer: "No" },
    { subject: "react", question: "Which hook is used to access the DOM directly?", options: ["useRef", "useEffect", "useDOM"], correctAnswer: "useRef" },
    { subject: "react", question: "What does 'Lifting State Up' mean?", options: ["Moving state to a parent", "Moving state to a child", "Removing state"], correctAnswer: "Moving state to a parent" },
    { subject: "react", question: "What is Redux used for?", options: ["State Management", "Routing", "Styling"], correctAnswer: "State Management" },
    { subject: "react", question: "What is the 'children' prop?", options: ["Content between tags", "List of child IDs", "A special function"], correctAnswer: "Content between tags" },
    { subject: "react", question: "Which hook triggers on every render if no dependency array?", options: ["useEffect", "useMemo", "useCallback"], correctAnswer: "useEffect" },
    { subject: "react", question: "What is a Higher-Order Component?", options: ["Function returning a component", "A root component", "A component with many props"], correctAnswer: "Function returning a component" },
    { subject: "react", question: "What is the use of 'useReducer'?", options: ["Handling complex state logic", "Simple state", "API calls"], correctAnswer: "Handling complex state logic" },
    { subject: "react", question: "What is Babel?", options: ["A JS compiler", "A Testing tool", "A Database"], correctAnswer: "A JS compiler" },
    { subject: "react", question: "How do you conditionally render an element?", options: ["Ternary operator", "For loop", "Switch case"], correctAnswer: "Ternary operator" },
    { subject: "react", question: "What is the Virtual DOM?", options: ["In-memory representation of UI", "A physical copy of the DOM", "A CSS framework"], correctAnswer: "In-memory representation of UI" },
    { subject: "react", question: "Which hook is used for persistent values?", options: ["useRef", "useState", "useMemo"], correctAnswer: "useRef" },
    { subject: "react", question: "What is the correct way to update state?", options: ["setState()", "state = newValue", "update(state)"], correctAnswer: "setState()" },

    // --- DSA (25 Questions) ---
    { subject: "dsa", question: "Time complexity of BST search?", options: ["O(log n)", "O(n)", "O(1)"], correctAnswer: "O(log n)" },
    { subject: "dsa", question: "What is a stack?", options: ["LIFO", "FIFO", "Random Access"], correctAnswer: "LIFO" },
    { subject: "dsa", question: "Which data structure uses FIFO?", options: ["Queue", "Stack", "Tree"], correctAnswer: "Queue" },
    { subject: "dsa", question: "Average complexity of QuickSort?", options: ["O(n log n)", "O(n^2)", "O(n)"], correctAnswer: "O(n log n)" },
    { subject: "dsa", question: "Linear search worst-case complexity?", options: ["O(n)", "O(1)", "O(log n)"], correctAnswer: "O(n)" },
    { subject: "dsa", question: "Which traversal gives sorted BST elements?", options: ["Inorder", "Preorder", "Postorder"], correctAnswer: "Inorder" },
    { subject: "dsa", question: "Recursion uses which data structure?", options: ["Stack", "Queue", "Heap"], correctAnswer: "Stack" },
    { subject: "dsa", question: "Dijkstra's algorithm finds what?", options: ["Shortest Path", "Maximum Flow", "Minimum Cut"], correctAnswer: "Shortest Path" },
    { subject: "dsa", question: "Which sort is the fastest in practice?", options: ["Quick Sort", "Bubble Sort", "Insertion Sort"], correctAnswer: "Quick Sort" },
    { subject: "dsa", question: "What is a Max-Heap?", options: ["Root is largest", "Root is smallest", "Random root"], correctAnswer: "Root is largest" },
    { subject: "dsa", question: "What is a Linked List?", options: ["Linear nodes", "Hierarchical nodes", "Non-linear nodes"], correctAnswer: "Linear nodes" },
    { subject: "dsa", question: "Complexity of adding to start of Linked List?", options: ["O(1)", "O(n)", "O(log n)"], correctAnswer: "O(1)" },
    { subject: "dsa", question: "Which algorithm uses Divide and Conquer?", options: ["Merge Sort", "Linear Search", "Bubble Sort"], correctAnswer: "Merge Sort" },
    { subject: "dsa", question: "What is Dynamic Programming?", options: ["Solving subproblems once", "Running code faster", "A type of database"], correctAnswer: "Solving subproblems once" },
    { subject: "dsa", question: "Space complexity of Adjacency Matrix?", options: ["O(V^2)", "O(V)", "O(E)"], correctAnswer: "O(V^2)" },
    { subject: "dsa", question: "What is an AVL Tree?", options: ["Self-balancing BST", "Binary Heap", "Unbalanced Tree"], correctAnswer: "Self-balancing BST" },
    { subject: "dsa", question: "Complexity of Binary Search?", options: ["O(log n)", "O(n)", "O(1)"], correctAnswer: "O(log n)" },
    { subject: "dsa", question: "Which data structure is used for BFS?", options: ["Queue", "Stack", "Linked List"], correctAnswer: "Queue" },
    { subject: "dsa", question: "What is a Hash Table?", options: ["Key-value mapping", "Hierarchical data", "Linear array only"], correctAnswer: "Key-value mapping" },
    { subject: "dsa", question: "Height of an empty tree?", options: ["-1", "0", "1"], correctAnswer: "-1" },
    { subject: "dsa", question: "Which sort is stable?", options: ["Merge Sort", "Quick Sort", "Selection Sort"], correctAnswer: "Merge Sort" },
    { subject: "dsa", question: "Complexity of array access by index?", options: ["O(1)", "O(n)", "O(log n)"], correctAnswer: "O(1)" },
    { subject: "dsa", question: "DFS uses which traversal method?", options: ["Stack/Recursion", "Queue", "Matrix"], correctAnswer: "Stack/Recursion" },
    { subject: "dsa", question: "What is a complete binary tree?", options: ["Every level filled", "Only root filled", "All nodes have 1 child"], correctAnswer: "Every level filled" },
    { subject: "dsa", question: "What is a Graph cycle?", options: ["Path starting and ending at same node", "A type of node", "A linear path"], correctAnswer: "Path starting and ending at same node" },

    // --- JAVA (25 Questions) ---
    { subject: "java", question: "Which is not a Java feature?", options: ["Pointers", "OOP", "Dynamic"], correctAnswer: "Pointers" },
    { subject: "java", question: "Default value of boolean?", options: ["false", "true", "null"], correctAnswer: "false" },
    { subject: "java", question: "Keyword for inheritance?", options: ["extends", "implements", "inherits"], correctAnswer: "extends" },
    { subject: "java", question: "Which package contains basic classes?", options: ["java.lang", "java.util", "java.io"], correctAnswer: "java.lang" },
    { subject: "java", question: "What is JVM?", options: ["Java Virtual Machine", "Java Vital Model", "Java Visual Machine"], correctAnswer: "Java Virtual Machine" },
    { subject: "java", question: "Can we have multiple public classes in one file?", options: ["No", "Yes", "Depends on IDE"], correctAnswer: "No" },
    { subject: "java", question: "Constructor return type?", options: ["None", "void", "int"], correctAnswer: "None" },
    { subject: "java", question: "Which keyword prevents method overriding?", options: ["final", "static", "private"], correctAnswer: "final" },
    { subject: "java", question: "What is an interface?", options: ["Blueprint of a class", "A variable", "A type of object"], correctAnswer: "Blueprint of a class" },
    { subject: "java", question: "Which memory handles Object creation?", options: ["Heap", "Stack", "Register"], correctAnswer: "Heap" },
    { subject: "java", question: "What is Polymorphism?", options: ["One task in different ways", "Data hiding", "Code reusability"], correctAnswer: "One task in different ways" },
    { subject: "java", question: "Static method can access non-static data?", options: ["No", "Yes", "Sometimes"], correctAnswer: "No" },
    { subject: "java", question: "What is JRE?", options: ["Java Runtime Environment", "Java Remote Engine", "Java Real Edition"], correctAnswer: "Java Runtime Environment" },
    { subject: "java", question: "How many primitive data types in Java?", options: ["8", "10", "6"], correctAnswer: "8" },
    { subject: "java", question: "Which keyword is used for exception handling?", options: ["try", "catch", "both"], correctAnswer: "both" },
    { subject: "java", question: "What is the parent class of all classes?", options: ["Object", "Main", "Parent"], correctAnswer: "Object" },
    { subject: "java", question: "Which operator is used for comparison?", options: ["==", "=", "==="], correctAnswer: "==" },
    { subject: "java", question: "What is encapsulation?", options: ["Wrapping data and code", "Inheriting data", "Running code"], correctAnswer: "Wrapping data and code" },
    { subject: "java", question: "Which block always executes?", options: ["finally", "catch", "try"], correctAnswer: "finally" },
    { subject: "java", question: "Which keyword refers to the current object?", options: ["this", "super", "self"], correctAnswer: "this" },
    { subject: "java", question: "What is method overloading?", options: ["Same name, different parameters", "Same name, same parameters", "Different name"], correctAnswer: "Same name, different parameters" },
    { subject: "java", question: "Size of an int in Java?", options: ["4 bytes", "2 bytes", "8 bytes"], correctAnswer: "4 bytes" },
    { subject: "java", question: "Which keyword is used to access parent methods?", options: ["super", "this", "parent"], correctAnswer: "super" },
    { subject: "java", question: "What is an abstract class?", options: ["Cannot be instantiated", "Must be final", "Must be static"], correctAnswer: "Cannot be instantiated" },
    { subject: "java", question: "Which method converts object to string?", options: ["toString()", "convertString()", "getString()"], correctAnswer: "toString()" },

    // --- PYTHON (25 Questions) ---
    { subject: "python", question: "How do you start a comment?", options: ["#", "//", "/*"], correctAnswer: "#" },
    { subject: "python", question: "Which is not a legal variable name?", options: ["2my-var", "my_var", "_myvar"], correctAnswer: "2my-var" },
    { subject: "python", question: "Which collection is ordered and unchangeable?", options: ["Tuple", "List", "Set"], correctAnswer: "Tuple" },
    { subject: "python", question: "Correct way to create a function?", options: ["def myFunction():", "create myFunction():", "function myFunction():"], correctAnswer: "def myFunction():" },
    { subject: "python", question: "What is the output of 2**3?", options: ["8", "6", "9"], correctAnswer: "8" },
    { subject: "python", question: "Which operator checks equality?", options: ["==", "=", "is"], correctAnswer: "==" },
    { subject: "python", question: "How do you check length of a list?", options: ["len()", "length()", "size()"], correctAnswer: "len()" },
    { subject: "python", question: "What is PEP 8?", options: ["Style guide", "Python version", "Library"], correctAnswer: "Style guide" },
    { subject: "python", question: "Which list method adds an element?", options: ["append()", "add()", "insert()"], correctAnswer: "append()" },
    { subject: "python", question: "Correct extension for Python files?", options: [".py", ".pt", ".pyt"], correctAnswer: ".py" },
    { subject: "python", question: "What is a 'lambda' function?", options: ["Anonymous function", "Built-in function", "Recursive function"], correctAnswer: "Anonymous function" },
    { subject: "python", question: "How to remove whitespace from both sides?", options: ["strip()", "trim()", "cut()"], correctAnswer: "strip()" },
    { subject: "python", question: "Which keyword is used for loops?", options: ["for", "loop", "foreach"], correctAnswer: "for" },
    { subject: "python", question: "What is range(5) equivalent to?", options: ["0 to 4", "1 to 5", "0 to 5"], correctAnswer: "0 to 4" },
    { subject: "python", question: "Which collection is unordered and indexed?", options: ["Dictionary", "List", "Tuple"], correctAnswer: "Dictionary" },
    { subject: "python", question: "How do you handle exceptions?", options: ["try/except", "try/catch", "error/handle"], correctAnswer: "try/except" },
    { subject: "python", question: "What is the result of 10 // 3?", options: ["3", "3.33", "4"], correctAnswer: "3" },
    { subject: "python", question: "Which keyword imports a module?", options: ["import", "using", "include"], correctAnswer: "import" },
    { subject: "python", question: "How to insert a value at a specific index?", options: ["insert()", "add()", "push()"], correctAnswer: "insert()" },
    { subject: "python", question: "What is 'None' in Python?", options: ["Null value", "0", "False"], correctAnswer: "Null value" },
    { subject: "python", question: "Is Python case sensitive?", options: ["Yes", "No", "Depends"], correctAnswer: "Yes" },
    { subject: "python", question: "Which function returns a list of keys?", options: ["keys()", "getKeys()", "listKeys()"], correctAnswer: "keys()" },
    { subject: "python", question: "What is a 'docstring'?", options: ["Documentation comment", "String variable", "Print statement"], correctAnswer: "Documentation comment" },
    { subject: "python", question: "How do you create a set?", options: ["{1, 2}", "[1, 2]", "(1, 2)"], correctAnswer: "{1, 2}" },
    { subject: "python", question: "Which module is for math functions?", options: ["math", "maths", "calculation"], correctAnswer: "math" },

    // for C++

 { subject: "c++", question: "Who developed C++?", options: ["Bjarne Stroustrup", "Dennis Ritchie", "James Gosling"], correctAnswer: "Bjarne Stroustrup" },
{ subject: "c++", question: "Which operator is used for input?", options: [">>", "<<", "=="], correctAnswer: ">>" },
{ subject: "c++", question: "What is a class in C++?", options: ["Blueprint for objects", "A primitive data type", "A function"], correctAnswer: "Blueprint for objects" },
{ subject: "c++", question: "Which feature of OOP allows code reusability?", options: ["Inheritance", "Encapsulation", "Polymorphism"], correctAnswer: "Inheritance" },
{ subject: "c++", question: "What is a virtual function?", options: ["Function for dynamic binding", "A function with no body", "A private function"], correctAnswer: "Function for dynamic binding" },
{ subject: "c++", question: "Which header file is used for I/O?", options: ["<iostream>", "<stdio.h>", "<conio.h>"], correctAnswer: "<iostream>" },
{ subject: "c++", question: "What is 'this' pointer?", options: ["Pointer to current object", "Pointer to parent", "A null pointer"], correctAnswer: "Pointer to current object" },
{ subject: "c++", question: "Which keyword is used for a constant?", options: ["const", "final", "static"], correctAnswer: "const" },
{ subject: "c++", question: "C++ is which type of language?", options: ["Multi-paradigm", "Procedural only", "Strictly Functional"], correctAnswer: "Multi-paradigm" },
{ subject: "c++", question: "What is the size of 'char' in C++?", options: ["1 byte", "2 bytes", "4 bytes"], correctAnswer: "1 byte" },
{ subject: "c++", question: "What is an inline function?", options: ["Function expanded at call", "Function inside a class", "Function with 1 line"], correctAnswer: "Function expanded at call" },
{ subject: "c++", question: "Which operator cannot be overloaded?", options: ["::", "+", "-"], correctAnswer: "::" },
{ subject: "c++", question: "What is a constructor?", options: ["Initializes an object", "Deletes an object", "A type of loop"], correctAnswer: "Initializes an object" },
{ subject: "c++", question: "What is a destructor name preceded by?", options: ["Tilde (~)", "Hash (#)", "Dollar ($)"], correctAnswer: "Tilde (~)" },
{ subject: "c++", question: "What is friend function?", options: ["Non-member accessing private data", "Member of class", "Global function"], correctAnswer: "Non-member accessing private data" },
{ subject: "c++", question: "Which access specifier is default in class?", options: ["private", "public", "protected"], correctAnswer: "private" },
{ subject: "c++", question: "What is abstraction?", options: ["Hiding complexity", "Wrapping data", "Multiple forms"], correctAnswer: "Hiding complexity" },
{ subject: "c++", question: "What is template in C++?", options: ["Generic programming tool", "A CSS file", "A loop structure"], correctAnswer: "Generic programming tool" },
{ subject: "c++", question: "Exception handling uses which keyword?", options: ["try", "throw", "All of these"], correctAnswer: "All of these" },
{ subject: "c++", question: "What is STL?", options: ["Standard Template Library", "System Tool Library", "Simple Text Language"], correctAnswer: "Standard Template Library" },
{ subject: "c++", question: "Which loop is exit-controlled?", options: ["do-while", "for", "while"], correctAnswer: "do-while" },
{ subject: "c++", question: "Which keyword handles memory allocation?", options: ["new", "malloc", "alloc"], correctAnswer: "new" },
{ subject: "c++", question: "What is a pure virtual function?", options: ["Function with =0", "Function in main", "Empty function"], correctAnswer: "Function with =0" },
{ subject: "c++", question: "How to define a block comment?", options: ["/* */", "//", "#"], correctAnswer: "/* */" },
{ subject: "c++", question: "What is function overloading?", options: ["Same name, different parameters", "Different name", "Recursion"], correctAnswer: "Same name, different parameters" },

//for C language
{ subject: "c", question: "Who developed C?", options: ["Dennis Ritchie", "Ken Thompson", "Bjarne"], correctAnswer: "Dennis Ritchie" },
{ subject: "c", question: "C is which type of language?", options: ["Procedural", "Object Oriented", "Assembly"], correctAnswer: "Procedural" },
{ subject: "c", question: "Which format specifier is for integer?", options: ["%d", "%f", "%c"], correctAnswer: "%d" },
{ subject: "c", question: "What is a pointer?", options: ["Stores address of variable", "Stores data", "A loop"], correctAnswer: "Stores address of variable" },
{ subject: "c", question: "What is the size of int on 32-bit?", options: ["4 bytes", "2 bytes", "8 bytes"], correctAnswer: "4 bytes" },
{ subject: "c", question: "Which keyword is used for structure?", options: ["struct", "class", "union"], correctAnswer: "struct" },
{ subject: "c", question: "Function used for output?", options: ["printf()", "scanf()", "cout"], correctAnswer: "printf()" },
{ subject: "c", question: "Symbol for address operator?", options: ["&", "*", "$"], correctAnswer: "&" },
{ subject: "c", question: "Default return type of function?", options: ["int", "void", "char"], correctAnswer: "int" },
{ subject: "c", question: "Which function is used for dynamic memory?", options: ["malloc()", "new", "create()"], correctAnswer: "malloc()" },
{ subject: "c", question: "How to end a C statement?", options: [";", ".", ":"], correctAnswer: ";" },
{ subject: "c", question: "What is a union?", options: ["Shared memory for members", "Distinct memory", "A loop"], correctAnswer: "Shared memory for members" },
{ subject: "c", question: "Index of first element in array?", options: ["0", "1", "-1"], correctAnswer: "0" },
{ subject: "c", question: "Which keyword skips a loop iteration?", options: ["continue", "break", "exit"], correctAnswer: "continue" },
{ subject: "c", question: "What is a local variable?", options: ["Inside a function", "Outside main", "Global"], correctAnswer: "Inside a function" },
{ subject: "c", question: "Which header is for string functions?", options: ["<string.h>", "<stdio.h>", "<math.h>"], correctAnswer: "<string.h>" },
{ subject: "c", question: "What is recursion?", options: ["Function calling itself", "A loop", "Function calling main"], correctAnswer: "Function calling itself" },
{ subject: "c", question: "What is the NULL pointer?", options: ["Pointer pointing nowhere", "Pointer to 0", "Dangling pointer"], correctAnswer: "Pointer pointing nowhere" },
{ subject: "c", question: "What is a string in C?", options: ["Array of characters", "A primitive type", "A class"], correctAnswer: "Array of characters" },
{ subject: "c", question: "Which keyword defines an enumeration?", options: ["enum", "list", "set"], correctAnswer: "enum" },
{ subject: "c", question: "Binary search requires what?", options: ["Sorted array", "Unsorted array", "Linked List"], correctAnswer: "Sorted array" },
{ subject: "c", question: "What is 'static' variable?", options: ["Retains value between calls", "Constant", "Fast variable"], correctAnswer: "Retains value between calls" },
{ subject: "c", question: "How to calculate size of variable?", options: ["sizeof()", "size()", "len()"], correctAnswer: "sizeof()" },
{ subject: "c", question: "What is a macro?", options: ["Pre-processor directive", "A function", "A variable"], correctAnswer: "Pre-processor directive" },
{ subject: "c", question: "Exit code for success?", options: ["0", "1", "-1"], correctAnswer: "0" },

//for Html
{ subject: "html", question: "What does HTML stand for?", options: ["HyperText Markup Language", "High Tech Machine Language", "Hyperlink Text Language"], correctAnswer: "HyperText Markup Language" },
{ subject: "html", question: "Which tag is for the largest heading?", options: ["<h1>", "<h6>", "<head>"], correctAnswer: "<h1>" },
{ subject: "html", question: "Correct tag for line break?", options: ["<br>", "<lb>", "<break>"], correctAnswer: "<br>" },
{ subject: "html", question: "How to make a hyperlink?", options: ["<a href='...'>", "<a>", "<link>"], correctAnswer: "<a href='...'>" },
{ subject: "html", question: "Tag used for an image?", options: ["<img>", "<pic>", "<src>"], correctAnswer: "<img>" },
{ subject: "html", question: "What is the root element?", options: ["<html>", "<body>", "<head>"], correctAnswer: "<html>" },
{ subject: "html", question: "How to create an ordered list?", options: ["<ol>", "<ul>", "<li>"], correctAnswer: "<ol>" },
{ subject: "html", question: "Which attribute is used for alt text?", options: ["alt", "title", "src"], correctAnswer: "alt" },
{ subject: "html", question: "Tag for a table row?", options: ["<tr>", "<td>", "<th>"], correctAnswer: "<tr>" },
{ subject: "html", question: "How to create a checkbox?", options: ["<input type='checkbox'>", "<check>", "<checkbox>"], correctAnswer: "<input type='checkbox'>" },
{ subject: "html", question: "Which tag is for a button?", options: ["<button>", "<btn>", "<input type='btn'>"], correctAnswer: "<button>" },
{ subject: "html", question: "Which tag defines the page title?", options: ["<title>", "<head>", "<meta>"], correctAnswer: "<title>" },
{ subject: "html", question: "Tag used for a paragraph?", options: ["<p>", "<span>", "<div>"], correctAnswer: "<p>" },
{ subject: "html", question: "Correct HTML5 doctype?", options: ["<!DOCTYPE html>", "<html>", "<doctype>"], correctAnswer: "<!DOCTYPE html>" },
{ subject: "html", question: "How to make a dropdown list?", options: ["<select>", "<list>", "<dropdown>"], correctAnswer: "<select>" },
{ subject: "html", question: "Attribute for unique ID?", options: ["id", "class", "name"], correctAnswer: "id" },
{ subject: "html", question: "Tag for bold text?", options: ["<b>", "<bold>", "<strong>"], correctAnswer: "<b>" },
{ subject: "html", question: "Tag for italics?", options: ["<i>", "<italic>", "<em>"], correctAnswer: "<i>" },
{ subject: "html", question: "How to embed video?", options: ["<video>", "<movie>", "<media>"], correctAnswer: "<video>" },
{ subject: "html", question: "Tag for a section?", options: ["<section>", "<div>", "<article>"], correctAnswer: "<section>" },
{ subject: "html", question: "What is a semantic tag?", options: ["Tag with meaning", "Style tag", "Script tag"], correctAnswer: "Tag with meaning" },
{ subject: "html", question: "How to add a comment?", options: ["", "//", "/* */"], correctAnswer: "" },
{ subject: "html", question: "Tag for horizontal rule?", options: ["<hr>", "<line>", "<br>"], correctAnswer: "<hr>" },
{ subject: "html", question: "Which input type is for hidden data?", options: ["hidden", "secret", "none"], correctAnswer: "hidden" },
{ subject: "html", question: "What does target='_blank' do?", options: ["Opens in new tab", "Opens in same", "Reloads"], correctAnswer: "Opens in new tab" },

//For CSS
{ subject: "css", question: "What does CSS stand for?", options: ["Cascading Style Sheets", "Colorful Style Sheets", "Creative Style Sheets"], correctAnswer: "Cascading Style Sheets" },
{ subject: "css", question: "Which property changes text color?", options: ["color", "text-color", "bg-color"], correctAnswer: "color" },
{ subject: "css", question: "Selector for an ID?", options: ["#", ".", "*"], correctAnswer: "#" },
{ subject: "css", question: "Selector for a class?", options: [".", "#", "->"], correctAnswer: "." },
{ subject: "css", question: "How to change font size?", options: ["font-size", "text-size", "size"], correctAnswer: "font-size" },
{ subject: "css", question: "Which property adds space inside border?", options: ["padding", "margin", "border-spacing"], correctAnswer: "padding" },
{ subject: "css", question: "How to add space outside border?", options: ["margin", "padding", "gap"], correctAnswer: "margin" },
{ subject: "css", question: "Default value of position?", options: ["static", "relative", "absolute"], correctAnswer: "static" },
{ subject: "css", question: "Property for background image?", options: ["background-image", "bg-img", "image"], correctAnswer: "background-image" },
{ subject: "css", question: "How to make text bold?", options: ["font-weight: bold", "text: bold", "bold: yes"], correctAnswer: "font-weight: bold" },
{ subject: "css", question: "Property to center text?", options: ["text-align: center", "align: center", "vertical-align"], correctAnswer: "text-align: center" },
{ subject: "css", question: "What is Z-index?", options: ["Stack order", "Width", "Zoom level"], correctAnswer: "Stack order" },
{ subject: "css", question: "How to hide an element but keep space?", options: ["visibility: hidden", "display: none", "opacity: 0"], correctAnswer: "visibility: hidden" },
{ subject: "css", question: "Which layout tool uses columns/rows?", options: ["Grid", "Flexbox", "Floats"], correctAnswer: "Grid" },
{ subject: "css", question: "How to make a responsive layout?", options: ["Media Queries", "Styles", "Divs"], correctAnswer: "Media Queries" },
{ subject: "css", question: "Property for border width?", options: ["border-width", "thickness", "border-size"], correctAnswer: "border-width" },
{ subject: "css", question: "How to change cursor style?", options: ["cursor", "pointer", "mouse"], correctAnswer: "cursor" },
{ subject: "css", question: "What is Flexbox used for?", options: ["1D Layouts", "3D Graphics", "Animations"], correctAnswer: "1D Layouts" },
{ subject: "css", question: "Property for rounded corners?", options: ["border-radius", "corner-radius", "circle"], correctAnswer: "border-radius" },
{ subject: "css", question: "Which unit is relative to font size?", options: ["em", "px", "cm"], correctAnswer: "em" },
{ subject: "css", question: "Property for shadow?", options: ["box-shadow", "shadow", "drop-shadow"], correctAnswer: "box-shadow" },
{ subject: "css", question: "How to repeat background?", options: ["background-repeat", "repeat", "bg-loop"], correctAnswer: "background-repeat" },
{ subject: "css", question: "CSS file link goes where?", options: ["<head>", "<body>", "<footer>"], correctAnswer: "<head>" },
{ subject: "css", question: "Property for transparency?", options: ["opacity", "transparent", "alpha"], correctAnswer: "opacity" },
{ subject: "css", question: "Property for bullet style?", options: ["list-style-type", "bullet-style", "marker"], correctAnswer: "list-style-type" },

//for java script
{ subject: "javascript", question: "Which keyword defines a constant?", options: ["const", "let", "var"], correctAnswer: "const" },
{ subject: "javascript", question: "How to output to console?", options: ["console.log()", "print()", "alert()"], correctAnswer: "console.log()" },
{ subject: "javascript", question: "What is DOM?", options: ["Document Object Model", "Data Object Model", "Digital Object Model"], correctAnswer: "Document Object Model" },
{ subject: "javascript", question: "Which operator checks value and type?", options: ["===", "==", "="], correctAnswer: "===" },
{ subject: "javascript", question: "What is a function?", options: ["Reusable code block", "A loop", "A variable type"], correctAnswer: "Reusable code block" },
{ subject: "javascript", question: "How to select ID element?", options: ["getElementById", "getElementClass", "queryID"], correctAnswer: "getElementById" },
{ subject: "javascript", question: "What is an array?", options: ["List of items", "A single value", "A loop"], correctAnswer: "List of items" },
{ subject: "javascript", question: "How to add element to array?", options: ["push()", "add()", "append()"], correctAnswer: "push()" },
{ subject: "javascript", question: "What is an object?", options: ["Key-value pairs", "A function", "A single string"], correctAnswer: "Key-value pairs" },
{ subject: "javascript", question: "Which keyword defines block-scope variable?", options: ["let", "var", "scope"], correctAnswer: "let" },
{ subject: "javascript", question: "What is an event?", options: ["User interaction", "A function", "A loop"], correctAnswer: "User interaction" },
{ subject: "javascript", question: "How to write 'if' statement?", options: ["if (x > y)", "if x > y then", "if: x > y"], correctAnswer: "if (x > y)" },
{ subject: "javascript", question: "Which function converts string to int?", options: ["parseInt()", "toInt()", "convert()"], correctAnswer: "parseInt()" },
{ subject: "javascript", question: "What is an arrow function?", options: ["() => {}", "function()", "arrow{}"], correctAnswer: "() => {}" },
{ subject: "javascript", question: "How to delay code execution?", options: ["setTimeout()", "wait()", "delay()"], correctAnswer: "setTimeout()" },
{ subject: "javascript", question: "What is an asynchronous function?", options: ["Runs in background", "Runs line by line", "Blocks UI"], correctAnswer: "Runs in background" },
{ subject: "javascript", question: "Symbol for template literals?", options: ["Backticks (`)", "Quotes (')", "Double quotes (\")"], correctAnswer: "Backticks (`)" },
{ subject: "javascript", question: "Which method joins two arrays?", options: ["concat()", "join()", "merge()"], correctAnswer: "concat()" },
{ subject: "javascript", question: "What is 'this' keyword?", options: ["Current context", "Global variable", "A function name"], correctAnswer: "Current context" },
{ subject: "javascript", question: "How to iterate over an array?", options: ["forEach()", "loop()", "iterate()"], correctAnswer: "forEach()" },
{ subject: "javascript", question: "What is JSON?", options: ["Data format", "A library", "A database"], correctAnswer: "Data format" },
{ subject: "javascript", question: "Keyword to handle errors?", options: ["try/catch", "if/else", "error()"], correctAnswer: "try/catch" },
{ subject: "javascript", question: "Which method removes last item?", options: ["pop()", "shift()", "delete()"], correctAnswer: "pop()" },
{ subject: "javascript", question: "What is a Promise?", options: ["Async operation result", "A variable", "A loop"], correctAnswer: "Async operation result" },
{ subject: "javascript", question: "What does 'null' mean?", options: ["Intentional empty value", "Undefined", "0"], correctAnswer: "Intentional empty value" },

//for node js
{ subject: "node js", question: "Node.js is what?", options: ["JavaScript Runtime", "Programming Language", "Library"], correctAnswer: "JavaScript Runtime" },
{ subject: "node js", question: "Which engine powers Node.js?", options: ["V8", "SpiderMonkey", "Chakra"], correctAnswer: "V8" },
{ subject: "node js", question: "How to import a module (CommonJS)?", options: ["require()", "import", "using"], correctAnswer: "require()" },
{ subject: "node js", question: "What is npm?", options: ["Node Package Manager", "New Project Model", "Node Program Maker"], correctAnswer: "Node Package Manager" },
{ subject: "node js", question: "What is 'package.json'?", options: ["Project metadata", "A script file", "A CSS file"], correctAnswer: "Project metadata" },
{ subject: "node js", question: "Which module handles file systems?", options: ["fs", "path", "http"], correctAnswer: "fs" },
{ subject: "node js", question: "How to initialize a new project?", options: ["npm init", "npm start", "npm install"], correctAnswer: "npm init" },
{ subject: "node js", question: "Node.js is single-threaded?", options: ["Yes", "No", "Depends"], correctAnswer: "Yes" },
{ subject: "node js", question: "What is the Event Loop?", options: ["Handles async operations", "A type of loop", "A function"], correctAnswer: "Handles async operations" },
{ subject: "node js", question: "How to install a package?", options: ["npm install <pkg>", "npm add <pkg>", "get <pkg>"], correctAnswer: "npm install <pkg>" },
{ subject: "node js", question: "What is REPL?", options: ["Interactive shell", "A debugger", "A library"], correctAnswer: "Interactive shell" },
{ subject: "node js", question: "Which module creates a server?", options: ["http", "net", "url"], correctAnswer: "http" },
{ subject: "node js", question: "What is a Buffer?", options: ["Handles binary data", "A loop", "A string"], correctAnswer: "Handles binary data" },
{ subject: "node js", question: "What is '__dirname'?", options: ["Directory name of current script", "Parent directory", "Root"], correctAnswer: "__dirname" },
{ subject: "node js", question: "What is a stream?", options: ["Reading data piece by piece", "A continuous loop", "A function"], correctAnswer: "Reading data piece by piece" },
{ subject: "node js", question: "Node.js is built on which paradigm?", options: ["Event-driven", "Object-oriented", "Procedural"], correctAnswer: "Event-driven" },
{ subject: "node js", question: "What does 'non-blocking I/O' mean?", options: ["Does not wait for task completion", "Blocks until done", "Slow"], correctAnswer: "Does not wait for task completion" },
{ subject: "node js", question: "What is an EventEmitter?", options: ["Class to handle events", "A variable", "A loop"], correctAnswer: "Class to handle events" },
{ subject: "node js", question: "Which function reads a file synchronously?", options: ["readFileSync()", "readFile()", "read()"], correctAnswer: "readFileSync()" },
{ subject: "node js", question: "What is the purpose of 'path' module?", options: ["Working with file paths", "Connecting to DB", "Routing"], correctAnswer: "Working with file paths" },
{ subject: "node js", question: "How to run a script 'app.js'?", options: ["node app.js", "npm app.js", "run app.js"], correctAnswer: "node app.js" },
{ subject: "node js", question: "What is 'process.env'?", options: ["Environment variables", "A function", "Node config"], correctAnswer: "Environment variables" },
{ subject: "node js", question: "What is Middleware?", options: ["Function between request/response", "A database", "Frontend tool"], correctAnswer: "Function between request/response" },
{ subject: "node js", question: "What is a callback?", options: ["Function passed as argument", "A loop", "A string"], correctAnswer: "Function passed as argument" },
{ subject: "node js", question: "Which module provides basic networking?", options: ["net", "os", "dns"], correctAnswer: "net" },

// for express js
{ subject: "express js", question: "What is Express.js?", options: ["Web framework for Node.js", "A Database", "A UI library"], correctAnswer: "Web framework for Node.js" },
{ subject: "express js", question: "How to initialize an Express app?", options: ["const app = express()", "express.start()", "init()"], correctAnswer: "const app = express()" },
{ subject: "express js", question: "Function for GET requests?", options: ["app.get()", "app.post()", "app.use()"], correctAnswer: "app.get()" },
{ subject: "express js", question: "What is 'app.use()' for?", options: ["Middleware", "Routing only", "Sending data"], correctAnswer: "Middleware" },
{ subject: "express js", question: "How to send a JSON response?", options: ["res.json()", "res.send()", "res.text()"], correctAnswer: "res.json()" },
{ subject: "express js", question: "What are route parameters?", options: ["Dynamic parts of URL", "Static data", "Middleware"], correctAnswer: "Dynamic parts of URL" },
{ subject: "express js", question: "How to access URL params?", options: ["req.params", "req.query", "req.body"], correctAnswer: "req.params" },
{ subject: "express js", question: "Function for POST requests?", options: ["app.post()", "app.get()", "app.put()"], correctAnswer: "app.post()" },
{ subject: "express js", question: "What is 'req.body' used for?", options: ["Form/JSON data", "URL parameters", "Headers"], correctAnswer: "req.body" },
{ subject: "express js", question: "How to set status code?", options: ["res.status()", "res.code()", "res.set()"], correctAnswer: "res.status()" },
{ subject: "express js", question: "What is a router?", options: ["Splits routing logic", "Connects to DB", "A server"], correctAnswer: "Splits routing logic" },
{ subject: "express js", question: "How to serve static files?", options: ["express.static()", "app.serve()", "app.get()"], correctAnswer: "express.static()" },
{ subject: "express js", question: "Which method is for updating data?", options: ["PUT", "GET", "DELETE"], correctAnswer: "PUT" },
{ subject: "express js", question: "Which method is for deleting data?", options: ["DELETE", "POST", "PATCH"], correctAnswer: "DELETE" },
{ subject: "express js", question: "What does 'next()' do in middleware?", options: ["Passes to next function", "Ends request", "Sends data"], correctAnswer: "Passes to next function" },
{ subject: "express js", question: "How to access query strings?", options: ["req.query", "req.params", "req.body"], correctAnswer: "req.query" },
{ subject: "express js", question: "Which module parses request bodies?", options: ["body-parser", "express.parse", "query-parser"], correctAnswer: "body-parser" },
{ subject: "express js", question: "How to redirect a user?", options: ["res.redirect()", "res.move()", "res.send()"], correctAnswer: "res.redirect()" },
{ subject: "express js", question: "What is 'cors'?", options: ["Cross-Origin Resource Sharing", "A database", "A UI tool"], correctAnswer: "Cross-Origin Resource Sharing" },
{ subject: "express js", question: "What is a template engine?", options: ["Renders HTML (Pug/EJS)", "A database", "CSS tool"], correctAnswer: "Renders HTML (Pug/EJS)" },
{ subject: "express js", question: "How to listen on a port?", options: ["app.listen()", "app.start()", "app.run()"], correctAnswer: "app.listen()" },
{ subject: "express js", question: "What is 'morgan' used for?", options: ["Logging", "Routing", "Auth"], correctAnswer: "Logging" },
{ subject: "express js", question: "Is Express opinionated?", options: ["No (Unopinionated)", "Yes", "Strict"], correctAnswer: "No (Unopinionated)" },
{ subject: "express js", question: "How to handle 404?", options: ["Catch-all route at end", "Specific 404 middleware", "Both"], correctAnswer: "Both" },
{ subject: "express js", question: "Express is written in what?", options: ["JavaScript", "C++", "Java"], correctAnswer: "JavaScript" },

//for networking
{ subject: "networking", question: "What does IP stand for?", options: ["Internet Protocol", "Internal Program", "Internet Post"], correctAnswer: "Internet Protocol" },
{ subject: "networking", question: "Which layer is the IP layer in OSI?", options: ["Network", "Transport", "Data Link"], correctAnswer: "Network" },
{ subject: "networking", question: "How many layers in OSI model?", options: ["7", "5", "4"], correctAnswer: "7" },
{ subject: "networking", question: "What is DNS?", options: ["Domain Name System", "Data Network System", "Domain Node System"], correctAnswer: "Domain Name System" },
{ subject: "networking", question: "What is the port for HTTP?", options: ["80", "443", "21"], correctAnswer: "80" },
{ subject: "networking", question: "What is the port for HTTPS?", options: ["443", "80", "25"], correctAnswer: "443" },
{ subject: "networking", question: "Which protocol is connection-oriented?", options: ["TCP", "UDP", "IP"], correctAnswer: "TCP" },
{ subject: "networking", question: "What is a Router?", options: ["Connects different networks", "Connects same network", "A type of cable"], correctAnswer: "Connects different networks" },
{ subject: "networking", question: "What is a Switch?", options: ["Connects devices on same LAN", "Connects LANs", "A protocol"], correctAnswer: "Connects devices on same LAN" },
{ subject: "networking", question: "What is a MAC address?", options: ["Physical address", "Logical address", "A server address"], correctAnswer: "Physical address" },
{ subject: "networking", question: "Which protocol sends emails?", options: ["SMTP", "POP3", "HTTP"], correctAnswer: "SMTP" },
{ subject: "networking", question: "What is DHCP?", options: ["Assigns IP addresses", "Domain service", "Routing protocol"], correctAnswer: "Assigns IP addresses" },
{ subject: "networking", question: "What is the loopback IP?", options: ["127.0.0.1", "192.168.1.1", "10.0.0.1"], correctAnswer: "127.0.0.1" },
{ subject: "networking", question: "What is a Gateway?", options: ["Entrance to another network", "A router port", "A firewall"], correctAnswer: "Entrance to another network" },
{ subject: "networking", question: "What does FTP stand for?", options: ["File Transfer Protocol", "File Text Program", "Fast Tool Protocol"], correctAnswer: "File Transfer Protocol" },
{ subject: "networking", question: "Which layer is for end-to-end delivery?", options: ["Transport", "Session", "Physical"], correctAnswer: "Transport" },
{ subject: "networking", question: "What is ICMP used for?", options: ["Error reporting (Ping)", "File transfer", "Web browsing"], correctAnswer: "Error reporting (Ping)" },
{ subject: "networking", question: "What is a Firewall?", options: ["Security barrier", "A router", "A cable"], correctAnswer: "Security barrier" },
{ subject: "networking", question: "What is Subnetting?", options: ["Dividing a network", "Naming a network", "A protocol"], correctAnswer: "Dividing a network" },
{ subject: "networking", question: "What is a VPN?", options: ["Virtual Private Network", "Visual Port Node", "Virtual Public Network"], correctAnswer: "Virtual Private Network" },
{ subject: "networking", question: "Size of IPv4 address?", options: ["32 bits", "64 bits", "128 bits"], correctAnswer: "32 bits" },
{ subject: "networking", question: "Size of IPv6 address?", options: ["128 bits", "32 bits", "64 bits"], correctAnswer: "128 bits" },
{ subject: "networking", question: "What is a LAN?", options: ["Local Area Network", "Large Area Network", "Link Area Node"], correctAnswer: "Local Area Network" },
{ subject: "networking", question: "What is NAT?", options: ["Network Address Translation", "Network Access Tool", "Node Area Type"], correctAnswer: "Network Address Translation" },
{ subject: "networking", question: "Which device operates at Physical layer?", options: ["Hub", "Router", "Switch"], correctAnswer: "Hub" },

//for sql
{ subject: "sql", question: "What does SQL stand for?", options: ["Structured Query Language", "Standard Query Link", "Simple Query List"], correctAnswer: "Structured Query Language" },
{ subject: "sql", question: "Statement to select data?", options: ["SELECT", "EXTRACT", "GET"], correctAnswer: "SELECT" },
{ subject: "sql", question: "Statement to update data?", options: ["UPDATE", "SAVE", "MODIFY"], correctAnswer: "UPDATE" },
{ subject: "sql", question: "Statement to delete data?", options: ["DELETE", "REMOVE", "DROP"], correctAnswer: "DELETE" },
{ subject: "sql", question: "How to insert new data?", options: ["INSERT INTO", "ADD NEW", "CREATE"], correctAnswer: "INSERT INTO" },
{ subject: "sql", question: "How to select all columns?", options: ["SELECT *", "SELECT ALL", "SELECT [ALL]"], correctAnswer: "SELECT *" },
{ subject: "sql", question: "Which clause filters records?", options: ["WHERE", "FILTER", "HAVING"], correctAnswer: "WHERE" },
{ subject: "sql", question: "What is a Primary Key?", options: ["Unique identifier", "Foreign key", "A string"], correctAnswer: "Unique identifier" },
{ subject: "sql", question: "What is a Foreign Key?", options: ["Link between tables", "Primary key", "Unique key"], correctAnswer: "Link between tables" },
{ subject: "sql", question: "How to sort results?", options: ["ORDER BY", "SORT BY", "GROUP BY"], correctAnswer: "ORDER BY" },
{ subject: "sql", question: "How to return unique values?", options: ["SELECT DISTINCT", "SELECT UNIQUE", "SELECT NEW"], correctAnswer: "SELECT DISTINCT" },
{ subject: "sql", question: "Which operator matches a pattern?", options: ["LIKE", "MATCH", "IN"], correctAnswer: "LIKE" },
{ subject: "sql", question: "Function to count rows?", options: ["COUNT()", "TOTAL()", "SUM()"], correctAnswer: "COUNT()" },
{ subject: "sql", question: "Which join returns matching records?", options: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN"], correctAnswer: "INNER JOIN" },
{ subject: "sql", question: "How to group identical data?", options: ["GROUP BY", "ORDER BY", "ORGANIZE"], correctAnswer: "GROUP BY" },
{ subject: "sql", question: "Function for average value?", options: ["AVG()", "MEAN()", "TOTAL()"], correctAnswer: "AVG()" },
{ subject: "sql", question: "How to delete a table structure?", options: ["DROP TABLE", "DELETE TABLE", "REMOVE TABLE"], correctAnswer: "DROP TABLE" },
{ subject: "sql", question: "What is a NULL value?", options: ["Empty field", "0", "Space"], correctAnswer: "Empty field" },
{ subject: "sql", question: "Which clause filters groups?", options: ["HAVING", "WHERE", "GROUP WHERE"], correctAnswer: "HAVING" },
{ subject: "sql", question: "How to add a column?", options: ["ALTER TABLE", "UPDATE TABLE", "ADD COLUMN"], correctAnswer: "ALTER TABLE" },
{ subject: "sql", question: "Command to create database?", options: ["CREATE DATABASE", "ADD DATABASE", "NEW DB"], correctAnswer: "CREATE DATABASE" },
{ subject: "sql", question: "What is an Index?", options: ["Speeds up retrieval", "A table", "A primary key"], correctAnswer: "Speeds up retrieval" },
{ subject: "sql", question: "Result of 'IN' operator?", options: ["Matches value in list", "Matches pattern", "Joins tables"], correctAnswer: "Matches value in list" },
{ subject: "sql", question: "What is ACID property?", options: ["Transaction reliability", "Database speed", "Data types"], correctAnswer: "Transaction reliability" },
{ subject: "sql", question: "Statement to select top records?", options: ["LIMIT / TOP", "FIRST", "MAX"], correctAnswer: "LIMIT / TOP" },
  ];
};